apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: ha
spec:
  version: ${imageTag}
  count: 1
  elasticsearchRef:
    name: ha
  http:
    service:
      spec:
        type: LoadBalancer # default is ClusterIP
