project_id = "elastic-observability"
region     = "us-central1"
team_name = "cloud-native-integrations-team"
es_password = "YfRCxmFgDxUeCiRUAkIm9Ex4"
es_user = "elastic"
es_host = "https://large-k8s.es.us-east1.gcp.elastic-cloud.com:9243"
