---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-metrics-faker
  labels:
    app: prometheus-metrics-faker
  annotations:
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
    name: metrics
  selector:
    app: prometheus-metrics-faker
